services:
  reflex:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      # Hot reload for development
      - ./src:/app
      # Don't sync node_modules and other build artifacts
      - /app/node_modules
      - /app/.web
      - /app/__pycache__
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend
    # Enable standard streams to see real-time logs
    tty: true
    stdin_open: true