services:
  reflex:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      # Hot reload for development
      - ./src:/src
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend
    # Enable standard streams to see real-time logs
    tty: true
    stdin_open: true