services:
  reflex:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend
    # Automatically restart if it crashes
    restart: unless-stopped