FROM python:3.12

WORKDIR /src

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./src .

ENV PYTHONPATH=/src

RUN python -m reflex init

EXPOSE 3000 8000

CMD ["python", "-m", "reflex", "run", "--env", "dev"]